### ISSUE TITLE
review my mutt scheme template?

### ISSUE THREAD

**Issue by josephholsten** [chriskempson/base16#101]
I've created a derivative of `mutt-colors-solarized` (it's been entirely rewritten twice now!) that assumes `base16-shell` is available, plus some other improvements. I'd love to get feedback about how this can better be part of the base16 ecosystem:

https://github.com/josephholsten/mutt-colors-contrejour

**Comment by chriskempson** [comment]
Is this a template or a scheme repo? Seems to be both combined in a single repo? Would suggest splitting them up and having base16-mutt and base16-contrejour unless there is some reason for combining them? Also a little confused by the compile script them is this a job that can't be handled by an existing builder? If so this should probably be mentioned in the readme.

**Comment by josephholsten** [comment]
well, it was originally a template + scheme in solarized, which I then broke apart into template and scheme. Now it's really just a configuration for mutt which depends upon `base16-shell` to set colors.

At the moment, the generator just swaps light and dark ordering. Since this is best handled in the scheme, I should remove it entirely.

**Comment by josephholsten** [comment]
All right, those changes have been made so it's really just two files, one of which is a readme ;-).

How do you feel about me renaming this to `base16-mutt`?

**Comment by chriskempson** [comment]
Yeah base16-mutt was the name I suggested in my previous comment 😉

**Comment by devhell** [comment]
Sorry to resurrect this, but would this be ready for inclusion as a template? I've been looking for a good way to theme mutt/neomutt for a long time (using 256 colors at least), and this is the best I've seen so far dealing with mutt's theming. :smile:
