### ISSUE TITLE
Jetbrains integration

### ISSUE THREAD

**Issue by Voonder** [chriskempson/base16#111]
Hello,

How to use base16 in Jetbrains IDE like Intellij ?

**Comment by chriskempson** [comment]
I don't believe that is supported sorry.

**Comment by Voonder** [comment]
I see.

**Information**
I try to convert the base16 with [TmTheme Editor](http://tmtheme-editor.herokuapp.com/) for integrate it to Intellij (specificly Android Studio) with an extension [TextMate bundles support](https://plugins.jetbrains.com/plugin/7221-textmate-bundles-support). 
This plugins is bugged. The two last update isn't available at Android Studio. So it isn't possible to use base16 on Intellij for now. Perhaps in ANdroid Studio 3.0, this solution will work.
WAIT AND SEE.

**Comment by chriskempson** [comment]
Closing as https://github.com/adilosa/base16-jetbrains exists.
