### ISSUE TITLE
Unable to switch between theme previews on Firefox

### ISSUE THREAD

**Issue by lokesh-krishna** [chriskempson/base16#122]
I am unable to switch the schemes or the languages in the theme preview box on the website. I am using Firefox 58. 

Everything works as intended on Chromium 61 though.

**Comment by chriskempson** [comment]
Thanks for spotting this, should be fixed now.

**Comment by lokesh-krishna** [comment]
I hope you're okay with me closing this issue then.

**Comment by chriskempson** [comment]
Of course 🙂
