### ISSUE TITLE
Theme preview site doesn't resolve

### ISSUE THREAD

**Issue by marktron** [chriskempson/base16#123]
The (excellent) preview site at https://chriskempson.github.io/base16/ does not seem to be up anymore. Did it move?

**Comment by chriskempson** [comment]
Yes, there's new version located at http://chriskempson.com/projects/base16

**Comment by marktron** [comment]
Cool, thanks! It would be nice if there was an easy way to preview a specific theme without having to cycle through them using the `j` and `k` keys, but not a big deal.

**Comment by chriskempson** [comment]
Agreed. I'm working on a better way of presenting schemes than a drop down.
