### ISSUE TITLE
Eighties theme repo

### ISSUE THREAD

**Issue by re1** [chriskempson/base16#133]
Hey there, I really like the eighties theme and would like to make a fork for a specific environment (KDE Breeze) but I could neither find a link to the base file nor the GitHub repository.

Nice work so far by the way!

**Comment by chriskempson** [comment]
For which editor

**Comment by re1** [comment]
I am specifically interested in Konsole, SublimeText 3 and JetBrains IDEs

**Comment by chriskempson** [comment]
Sorry for the delay in getting back to you. 

What is this fork for? I'm having trouble understanding what exactly you're trying to do sorry.

**Comment by re1** [comment]
I wanted to add a copy including the Arc and Breeze colors to fit into those desktop themes. It is not required by myself anymore but the repository is still missing.

**Comment by chriskempson** [comment]
I guess you'd have to fork a builder and and those two colour schemes or just included them in the scheme sources then.

I'm not clear on exactly what is missing sorry? If you're after a report containing the eighties scheme it's bundled with the default colours.

**Comment by re1** [comment]
That was the exakt problem, I could not find the repo.

**Comment by chriskempson** [comment]
Oh I see sorry. Yes I guess it isn't indicated anywhere that the theme belong to https://github.com/chriskempson/base16-default-schemes sorry!
