### ISSUE TITLE
My Color Theme

### ISSUE THREAD

**Issue by varmanishant** [chriskempson/base16#135]
Hello,

I have a color theme which I would like to share, please do have a look. I just call it Base16 Standard. If you think it is good, please consider adding it to the repository. Please let me know if you have suggestions.

[Image](https://imgur.com/a/WCLK6)

```
# Base16 Standard Dark
background = #101010
foreground = #eeeeee
cursor = #eeeeee
# black
color0 = #101010
color8 = #262626
# red
color1 = #f06060
color9 = #f06060
# green
color2 = #50c878
color10 = #50c878
# yellow
color3 = #d2b55b
color11 = #d2b55b
# blue
color4 = #128bd5
color12 = #128bd5
# magenta
color5 = #f75394
color13 = #f75394
# cyan
color6 = #1fd6ff
color14 = #1fd6ff
# white
color7 = #333333
color15 = #eeeeee

```

**Comment by chriskempson** [comment]
Looks nice but needs to be added to https://github.com/chriskempson/base16-schemes-source
