### ISSUE TITLE
Mac OS X Theme

### ISSUE THREAD

**Issue by stevestock** [chriskempson/base16#142]
It looks like [tomorrow-theme](https://github.com/chriskempson/tomorrow-theme/tree/master/OS%20X%20Terminal) had support for OS X.  Does base16 have a Mac OS X Theme?

**Comment by chriskempson** [comment]
I took a quick look at the readme for you (https://github.com/chriskempson/base16#template-repositories) and it looks like there is no support for Terminal so but you can theme iTerm2.
