### ISSUE TITLE
How to create or customise a theme?

### ISSUE THREAD

**Issue by avdd** [chriskempson/base16#143]
I just started using base16 for shell and vim, but I find none of the bundled themes is quite right for me in both environments.  I would like to customise a theme to my taste, but I cannot figure out how to go about this.  Is there a page that I've missed with some instructions?

**Comment by chriskempson** [comment]
Clone a Builder repo (https://github.com/chriskempson/base16#builder-repositories) in your preferred language and customise a scheme and/or templates to suit.
