### ISSUE TITLE
base16-nord: wrong color assignment

### ISSUE THREAD

**Issue by FrauH0lle** [chriskempson/base16#162]
Comparing screenshots showing the terminal from the Nord theme's website 
![grafik](https://user-images.githubusercontent.com/10484857/43348554-eb779b08-91fa-11e8-8eab-f2aa84f536de.png)

with my own one 
![bildschirmfoto vom 2018-07-28 00-13-33](https://user-images.githubusercontent.com/10484857/43348590-179d4458-91fb-11e8-9b2e-dc949af68e36.png)

I realized that the colors are not the same. 
For example, in the .XResources of base16-nord

```
*foreground:   base05
#ifdef background_opacity
*background:   [background_opacity]base00
#else
*background:   base00
#endif
*cursorColor:  base05

*color0:       base00
*color1:       base08
*color2:       base0B
*color3:       base0A
*color4:       base0D
*color5:       base0E
*color6:       base0C
*color7:       base05

*color8:       base03
*color9:       base09
*color10:      base01
*color11:      base02
*color12:      base04
*color13:      base06
*color14:      base0F
*color15: base07
```

vs Nord

```
*.foreground:   nord4
*.background:   nord0
*.cursorColor:  nord4
*fading: 35
*fadeColor: nord3

*.color0: nord1
*.color1: nord11
*.color2: nord14
*.color3: nord13
*.color4: nord9
*.color5: nord15
*.color6: nord8
*.color7: nord5
*.color8: nord3
*.color9: nord11
*.color10: nord14
*.color11: nord13
*.color12: nord9
*.color13: nord15
*.color14: nord7
*.color15: nord6
```

For example, base16 uses color 05 for the foreground whereas Nord uses color 04 (and some other differences). Would it be possible to fix the differences or are they intended?

**Comment by belak** [comment]
From what I can tell, the base16-nord theme is an attempt to map the nord colors onto the base16 palate. Because base16 is a generic builder for schemes and templates, we don't provide workarounds for specific schemes in the builder or the template repos.

http://chriskempson.com/projects/base16/ provides an overview of the base16 project and how the colors are mapped into templates (In general) and the [xresources template](https://github.com/chriskempson/base16-xresources/blob/master/templates/default.mustache) shows how we map them onto the 16 terminal colors.

**Comment by DonHugo69** [comment]
I see. It is just that in this case the base16 variant changes the feel of the Nord theme from the cold colors to warm colors (which, in my eyes, changes the overall feel of the theme)

I took a look at the theme templates and the builder process and modified the Nord yaml file to restore the cold feel of the theme. In case somebody is interested/for reference:

```
scheme: "Nord"
author: "arcticicestudio"
base00: "2E3440"
base01: "3B4252"
base02: "434C5E"
base03: "4C566A"
base04: "D8DEE9"
base05: "E5E9F0"
base06: "ECEFF4"
base07: "8FBCBB"
base08: "BF616A"
base09: "D08770"
base0A: "EBCB8B"
base0B: "A3BE8C"
base0C: "88C0D0"
base0D: "81A1C1"
base0E: "B48EAD"
base0F: "5E81AC"
```

**Comment by belak** [comment]
It may have been a mistake in the original port. That repo is here: https://github.com/ada-lovecraft/base16-nord-scheme

If you don't get a response and would like to replace it (or add a variation) we'll have to decide how to handle situations like that for the future.

**Comment by DonHugo69** [comment]
Thanks, I have opened an issue [here](https://github.com/ada-lovecraft/base16-nord-scheme/issues/1).

**Comment by DonHugo69** [comment]
It looks like the original author of the color scheme is not responding. Would it be possible for you to provide a fixed nord color scheme?

**Comment by belak** [comment]
The easiest way would be to make a scheme file repo and submit it. In this instance it might make sense to replace the original, but I'm not completely sure.

**Comment by spejamchr** [comment]
I created a pull request (https://github.com/ada-lovecraft/base16-nord-scheme/pull/2) to fix things with the original scheme. @ada-lovecraft seems more active on github now than she was a year ago.

**Comment by Corey-Keller** [comment]
@DonHugo69 @spejamchr @arcticicestudio May I suggest a better alternative: have @arcticicestudio create a repo, "nord-base16" for example and have the colorscheme there. Then we can have the actual theme maintainers be the ones maintaining the base16 theme.

**Comment by belak** [comment]
It looks like quite a while back, we actually migrated to the forked repo, so when this was imported into the new [base16-schemes](https://github.com/base16-project/base16-schemes) repo, this was fixed. Thanks for bringing this up!

**Comment by joshgoebel** [comment]
I find this thread related to https://github.com/base16-project/base16/issues/10#issuecomment-1171745224 (since once of it's explicit mentions was Nord)... I think the Base16 Nord theme (the examples I've seen so far) is just BROKEN entirely from the "intention" of Nord as exemplified by the theme in many non-base16 contexts.
