### ISSUE TITLE
Transfer the base16-xressources repo?

### ISSUE THREAD

**Issue by binaryplease** [chriskempson/base16#176]
Hi, 
as you communicated per email, you no longer maintain the repo base16-xresources. You told me to fork and submit a readme change. I have done so, however doing that I will loose the open issues and such. Would you consider tranferring it to me instead? That way, all is preserved.

Cheers,
Pablo

**Comment by chriskempson** [comment]
I tried but got the message 'binaryplease/base16-xresources already exists'. To be honest, there aren't a lot of issues open on this project so it should be fine I think.

**Comment by chriskempson** [comment]
I've transferred this to a base16-template org if you'd care to join an help maintain this repo? https://github.com/base16-templates/base16-xresources

**Comment by binaryplease** [comment]
Sure.

**Comment by chriskempson** [comment]
Invite sent 👍
