### ISSUE TITLE
Is it still alive?

### ISSUE THREAD

**Issue by actionless** [chriskempson/base16#181]
I am extensively using base16 themes as part of themix/oomox project.

If author abandoned the project i can continue maintaining it under themix-project github organization.

**Comment by belak** [comment]
The author pokes his head in every once in a while - to be honest, the most important things are the template repos.

It's a little frustrating having to wait a few months sometimes, but it's worth it to have all these in the same central place. There was an attempt a few years ago to fork the base16-builder (and it hasn't been updated since 2017), but in the end these repos are still used the most and still get updates.

**Comment by actionless** [comment]
i think the best would be if instead of forking original project would be moved to the organization still headed by the same author as now: https://github.com/chriskempson/base16/issues/74 but with more people to do such chore maintenance as updating source lists

**Comment by belak** [comment]
@chriskempson This issue directly asks about inactivity - there are 5 schemes waiting in the schemes repo, some of which have been open since December.

I'd be happy to help out with PR merging and other project wrangling if you're busy.

**Comment by reyemxela** [comment]
@chriskempson I'd also like to help if I can. Even just with PRs, like @belak said.

**Comment by belak** [comment]
I've outlined what I've been working on in https://github.com/chriskempson/base16/issues/74#issuecomment-497129667

If you've got any questions or concerns, that would probably be the best place to raise them.

**Comment by chriskempson** [comment]
@belak Sorry, seriously studying Japanese so I've had to put all my projects on hold. Would be grateful of any help, should I add you as a contributor?

**Comment by belak** [comment]
@chriskempson Thanks for responding! I'd be happy to help as a contributor. Which repos were you thinking? I've got the base repo, templates, and schemes up to date, but you also have base16-shell and base16-vim (among others as well).

Best of luck with learning Japanese. That's no small task.

**Comment by reyemxela** [comment]
@chriskempson @belak I'd also love to help out anywhere I'm able to. I definitely think this project is amazing, and has some huge potential to get even better.

**Comment by actionless** [comment]
@belak i think you need to add at least 2 more contributors to the org to reduce possible availability issues

**Comment by reyemxela** [comment]
So is everything moving to the new @base16-project, or did that change when chris popped in and said he could add contributors?

**Comment by belak** [comment]
I'm not completely sure - I'd prefer the new org, because it makes it easier for us to add other people (I'll add @chriskempson as another admin just in case) but I understand the desire to keep the project under the original umbrella.

**Comment by belak** [comment]
@chriskempson What are you hoping would happen here? Would we keep using these repos, or move them to @base16-project ? Either would work if there's something happening.

**Comment by chriskempson** [comment]
@belak I was just hoping I'd get some help with the repos in their current state and see how that works out. If the project did go down the organisation route at some point I'd want to transfer ownership of the three main repos to the organisation so ideally I'd quite like to have ownership of that organisation 😅

**Comment by reyemxela** [comment]
@chriskempson I'd love to help with the current repos. Also, thanks for merging the PR for my colorscheme! :D

**Comment by belak** [comment]
@chriskempson Earlier, you mentioned that you'd be willing to add me as a contributor. Is that still an option?

**Comment by chriskempson** [comment]
Yes of course. Just invited you both to the three main repos.

**Comment by belak** [comment]
Now that we've got a number of contributors who have been added, I think this can be closed now - the PRs have been cleaned up, and it should be easier to keep on top of it with multiple people.

**Comment by actionless** [comment]
so what's the upstream git url finally for base16 index?
