### ISSUE TITLE
in terminal emacs the current line highlight makes the text  under it unreadable

### ISSUE THREAD

**Issue by yilkalargaw** [chriskempson/base16#193]
I mostly use emacs in window mode and I like the base-16 themes. But for cases where I have to use it in terminal I like the terminal color sources so I set ```(setq base16-theme-256-color-source 'terminal)```. The current line highlight in this mode is some version of bright green and the text color is light-greyish or white so it renders it unreadable. I use the base16-solarized but I don't think that makes a difference because the terminal colors are affected by that.

**Comment by belak** [comment]
This sounds like it may be an issue with your configuration - are you using base16-shell?

**Comment by yilkalargaw** [comment]
Yep I use a base16-shell on st terminal-emulator

**Comment by belak** [comment]
If you're using base16-shell, you'll need to use `(setq base16-theme-256-color-source 'base16-shell)`

base16-shell overrides colors in some interesting ways which require a workaround in themes.

**Comment by yilkalargaw** [comment]
I got a way around it just by adding a custom-face for hl-line
