### ISSUE TITLE
base16 fzf and zathura maintainer

### ISSUE THREAD

**Issue by nicodebo** [chriskempson/base16#225]
Hi,
Not sure if this is the right place. I'm sorry if it is not.
I started these when I was jobless but now I don't have as much free time as before.
Does anyone is willing to take care of both of these repositories (maybe @fnune @InspectorMustache) ?:

~~https://github.com/nicodebo/base16-fzf~~ (-> maintained by fnune)
~~https://github.com/nicodebo/base16-zathura~~ (-> maintained by HaoZeke)

**Comment by fnune** [comment]
My own fork https://github.com/fnune/base16-fzf/ auto-updates, and I can take care of necessary manual updates as well.

**Comment by fnune** [comment]
About Zathura: I didn't know about the existence of this product before. Therefore I'd rather take care of the FZF repository.

But I assume both are simple, and it looks like the Zathura repository can also be auto-updated with an action.

**Comment by nicodebo** [comment]
Thanks for you interest, I wanted to give you the ownership of the fzf repository but I read that it might change the url of the repository which is going to break people scripts if they use the url. So instead I'll add you as a collaborator. If you are ok with this i'm adding you and of course you'll be free to do whatever you think is best in terms of updates, modifications,...

**Comment by fnune** [comment]
https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-a-user-account

I believe transferring the repository should be possible, and this would set up redirects for people's scripts, right?

Otherwise it's fine if I'm added as a collaborator.

**Comment by nicodebo** [comment]
Indeed, I misread that point.
But it also states that:  "The target account must not have a repository with the same name, or a fork in the same network." So you need to delete your fork.
I'm ok with both but i'd rather give you ownership.

**Comment by fnune** [comment]
I renamed my fork to `base16-fzf-test` so you can transfer it :)

**Comment by fnune** [comment]
If it's not working I suppose I can try deleting it

**Comment by fnune** [comment]
I misread that too: `or a fork in the same network`, I'll go ahead and delete my fork, then.

**Comment by fnune** [comment]
Alright, I've gone ahead and deleted it.

**Comment by nicodebo** [comment]
done ^^

**Comment by fnune** [comment]
Cool! Good luck finding a maintainer for the Zathura repo :)

**Comment by belak** [comment]
I'll change the relevant info in the readme and sources repo. Thanks for offering to maintain that!

**Comment by HaoZeke** [comment]
Hi. I use the zathura scheme a lot (thanks @nicodebo!) and I'd be willing to take over maintainace for it.

**Comment by nicodebo** [comment]
Hi
Thank you very much @HaoZeke.
I tried to transfer the ownership of the repository to you but it looks like you already have a fork.
Could you please delete it ?

**Comment by HaoZeke** [comment]
@nicodebo You're welcome I've deleted the fork now.

**Comment by nicodebo** [comment]
Done

**Comment by belak** [comment]
The maintainers in README.md have been updated, so I'm closing this for now. Thanks for handling all this!
