### ISSUE TITLE
A Swifty builder

### ISSUE THREAD

**Issue by neutralradiance** [chriskempson/base16#240]
Hello, I spent yesterday making a builder in swift. I hope for someone to test it out for me because I don't have internet on my computer just straight-up macOS. I just put some schemes and templates in the right place and it somehow worked out.
 [base16-builder-swift](https://github.com/neutralradiance/base16-builder-swift) 
thank you to @chriskempson and all the contributors to this project and thanks for listening

**Comment by belak** [comment]
Hey, sorry I haven't gotten to this yet - are you closing this because you don't want it merged any more or because it's taken too long?

**Comment by neutralradiance** [comment]
I thought I'd better make a pull request, but was also thinking no one would suggest it.

**Comment by neutralradiance** [comment]
> Hey, sorry I haven't gotten to this yet - are you closing this because you don't want it merged any more or because it's taken too long?

I'm thinking I better make it a base16 support package/builder for linux/macOS/iOS once I remove all the dependencies, except maybe, 'GRMustache.swift'.
