### ISSUE TITLE
Question about spec changes over time and updating older generators

### ISSUE THREAD

**Issue by joshgoebel** [chriskempson/base16#255]
Are the spec changes documented anywhere?  From 0.8 to 0.8.1 it looks like the only thing changed was a clarification about how slugs are generated.  Is that correct?

Thanks,
Josh

**Comment by joshgoebel** [comment]
### 0.8 => 0.8.1

> Where the slug is taken from the scheme file name made lowercase with spaces replaced with dashes and extension is taken from `/template/config.yaml`.

**Comment by joshgoebel** [comment]
Nevermind, I see now it's in the list itself just in condensed form. :)

**Comment by belak** [comment]
Glad you found it! There are some potential changes coming up in #250, but there haven't been any major changes in a while.
