### ISSUE TITLE
Should the spec specify HOW the warning should be issued?

### ISSUE THREAD

**Issue by joshgoebel** [chriskempson/base16#259]
What I have now:

```
    if (fs.existsSync(targetPath)) {
      console.warn(`Overwriting ${targetPath}\nYou have two schemes using the same slug name.`);
    }
```

I know you like explicitness... I was trying to figure out how helpful I need to be vs just marking this complete so I could say I've covered it.

**Comment by belak** [comment]
Strangely, I don't have any strong opinions on this. In this case I'd just say to do whatever you'd want to see if you ran into this issue.

**Comment by joshgoebel** [comment]
I'm happy with that then for an edge case that should never really come up hopefully.
