### ISSUE TITLE
Base16-ocean colors issue on Alacritty and Iterm2

### ISSUE THREAD

**Issue by gabrielbidula** [chriskempson/base16#262]
Hello,

I think the colors presented are not the correct colors for Base16-ocean, at least based on the below printscreen.

![Screenshot 2021-05-11 at 09 46 36](https://user-images.githubusercontent.com/1028654/117778421-e3d3f480-b23d-11eb-90d4-8f82408b30ed.png)

Maybe I am missing some configuration.
I am using nvim under OSX and both base16-vim and base16-shell are installed.

Left side using Iterm2 and the right side using Alacritty.

![Screenshot 2021-05-11 at 09 42 52](https://user-images.githubusercontent.com/1028654/117778161-a1121c80-b23d-11eb-8e63-7f3d40a72647.png)

Cheers

**Comment by belak** [comment]
Unfortunately, we no longer have a schemes preview page in the [base16-project](https://github.com/base16-project) org - eventually I'd like to change that, but because Chris's website seems to be down and there's no remaining ways to contact him, I'm closing this for now.
