### ISSUE TITLE
How should conflicts be handled?

### ISSUE THREAD

**Issue by belak** [chriskempson/base16#37]
It seems as though the schemes and templates repos are intended to have different repos which schemes and templates are cloned from. However, this means that the same theme could appear in multiple repos (and so could the same scheme) so how should that be handled? Is it worth having multiple levels of indirection? Maybe just a schemes.yml and a templates.yml would be enough.

**Comment by chriskempson** [comment]
Hopefully people won't be placing other peoples templates and schemes into repositories and adding them to the template and scheme source files :wink: 

I think the two files you mention already exist in the form of repos that are clone into a builder. This way every b16b builds the same list of schemes and templates.

**Comment by belak** [comment]
It sounds like the canonical thing to do would just be to error then.

The files I mentioned do already exist... it was just irking me that there's essentially *another* layer of indirection here, when it's just two repos... which are essentially only grabbed for one file.

**Comment by chriskempson** [comment]
An error would be good yes. As it stands though the template would just be overwritten. 

Oh sorry, if we don't have the two repos then wouldn't builder maintainers would all end up with different scheme and templates. Plus I thought it would be good if scheme/template authors only had to submit a PR to a single repo to have their work included across the board.

**Comment by belak** [comment]
I'd personally vote for explicitly mentioning erroring out for duplicate templates, even if it's not listed as a requirement for the spec. It can be easy to clobber files and wonder why they aren't there later.

That being said, unless other people have strong opinions on this, I could go either way... so feel free to close this with or without expicitly adding it to the spec.

**Comment by chriskempson** [comment]
It certainly not a bad idea though it might be best to only add the duplicate checking if it becomes a problem. I'd like the builders to be a simple as possible.

I'd like to leave this open in case others have ideas about this 😄

**Comment by belak** [comment]
Would it be reasonable to add this in as a soft recommendation? Like, it's not required for your builder to be spec compliant, but it's recommended?

**Comment by chriskempson** [comment]
I think a soft recommendation would mean some builders working differently to others. Either it's a good idea that needs implementing or it isn't. As it stands I can see why this is a good idea but I'm waiting until someone actually encounters this as an issue. I want a proper use case rather than a theoretical one.

**Comment by belak** [comment]
I did run into this. My builder followed a version of the spec where the slug was the slugified name. This caused a number of themes which had both a dark and a light variant (so they had different file names but the same "name") to conflict and only one of them was generated.

That was the cause of this: https://github.com/belak/base16-emacs/commit/cda22d67b161ba72d782cd888d626d688c66ecff

If there were warnings or errors in the builder it wouldn't have waited until someone reported the issue.

**Comment by chriskempson** [comment]
Thanks for offering up this use case.

> they had different file names but the same "name"

A scheme filename should be a slugified version of the name so it was the scheme file that was at fault and not your builder. That said I feel the use case you provided does require something to help prevent this mistake from being made in the future.

I think it would be nice if a builder notified you about duplicate template generation at the end of its output.

**Comment by belak** [comment]
That does seem like a reasonable addition. I believe my builder warns as soon as it sees that it's trying to build a theme that's already been built that iteration. It would be nice to see a similar safeguard in other builders.
