### ISSUE TITLE
Document /templates/[template name]/config.yml

### ISSUE THREAD

**Issue by belak** [chriskempson/base16#38]
It's not clear what should be in config.yml. There are obviously examples, but it would be nice for this to be explicit.

Here's the example from base16-vim:

```
default: 
    extension: .vim
    output: colors
```

This appears to use the .vim extension and set the output dir to `colors` in the base16-vim repo.

**Comment by chriskempson** [comment]
True, I plan to add two documents to this repo soon explaining the structure of scheme files and template config files.

**Comment by chriskempson** [comment]
https://github.com/chriskempson/base16/blob/master/file.md
