### ISSUE TITLE
Decide on .yaml or .yml

### ISSUE THREAD

**Issue by belak** [chriskempson/base16#39]
Both are commonly used extensions, but the documentation (and repos) seem to switch between .yaml and .yml files. It would be good to pick one and stick with it.

**Comment by chriskempson** [comment]
Agreed. I've been using `.yaml` lately as I felt it was slightly more descriptive. Either works for me if someone feels `.yml` is better.

**Comment by belak** [comment]
I don't have a strong preference as long as we stick to one. I think I may have made a mistake when I made this issue (when I created my sources file, I accidentally called it `sources.yml`) so I'll close this.
