### ISSUE TITLE
Code examples repository

### ISSUE THREAD

**Issue by chriskempson** [chriskempson/base16#41]
https://github.com/chriskempson/base16-vim/pull/77

When theming its pretty hard for me to theme languages that I don't use myself. A collection of example code files that I could open up in an editor would really help.

**Comment by KLVTZ** [comment]
@chriskempson do you still have the old examples that where listed before?

**Comment by KLVTZ** [comment]
https://chriskempson.github.io/base16/

**Comment by chriskempson** [comment]
https://github.com/chriskempson/base16-html-previews

**Comment by chriskempson** [comment]
Done: https://github.com/chriskempson/base16-language-examples
