### ISSUE TITLE
Ambiguities in builder spec

### ISSUE THREAD

**Issue by iamthad** [chriskempson/base16#47]
I've been working on my own builder (not yet ready to publish, but soon!), and I ran into a few things that weren't clear in the spec:

1. It doesn't seem to say anywhere that all the resulting files should start with "base16-"
2. It's not clear that the resulting files should be placed in a subdirectory of each template repo
3. The format of the -rgb and -hsl color outputs isn't clear.

I was able to figure these things out by looking at the reference implementation, but they probably should be in the spec.

**Comment by chriskempson** [comment]
Looking forward to seeing your builder 😄 Thanks for your feedback. I'll try and address the points you raised below:

1. I've added this to the readme.
2. There's a section that says "producing themes that will be output to the directories specified in  /templates/template_name/template/config.yaml". Could I improve this somehow?
3. I've added example of the -rgb and -hsl outputs to the readme.

**Comment by iamthad** [comment]
For 2, I took that to mean "directories (under the builder base directory) specified in config.yaml", rather than "directories (under each template) specified in that template's config.yaml". Not sure exactly how to re-word that in the best way.

**Comment by iamthad** [comment]
Here is my builder, btw. It's got a ways to go, but it does seem to work. https://github.com/iamthad/python_base16_builder

**Comment by chriskempson** [comment]
Thanks, added the work "template" before "directories". Hopefully that makes things clearer. Nice to see a python version. Be sure to add it to https://github.com/chriskempson/base16/blob/master/README.md#builder-repositories when you feel it is mature enough.
