### ISSUE TITLE
Need a format for real numbers 0-1

### ISSUE THREAD

**Issue by iamthad** [chriskempson/base16#48]
Some of the templates (e.g. iTerm2) need real numbers from 0 to 1, but there isn't a format like that.

**Comment by chriskempson** [comment]
Could you provide a bit more context please?

**Comment by iamthad** [comment]
Tried to clarify this a bit. Sorry for the long delay in response time.

**Comment by kreeger** [comment]
I know this is a bit of an oldie (?) but I would love for this to be part of the spec as well. I've been [using base16-builder-ruby](https://github.com/obahareth/base16-builder-ruby/blob/4bf9d69d5f668f9712a61b6933d54b986c577419/src/template.rb#L61) to build and test a new Xcode template generator, and I've extended the template variables to give me the output I need.

So for instance, in addition to this:

```ruby
data["#{base_key}-rgb-r"] = rgb[0]
data["#{base_key}-rgb-g"] = rgb[1]
data["#{base_key}-rgb-b"] = rgb[2]
```

I have this:

```ruby
data["#{base_key}-dec-r"] = (rgb[0].to_f / 255.0)
data["#{base_key}-dec-g"] = (rgb[1].to_f / 255.0)
data["#{base_key}-dec-b"] = (rgb[2].to_f / 255.0)
```

Xcode's color theme format seems to require colors specified in a decimal format (a numerical color value for each R, G, and B somewhere in between 0.0 and 1.0, so the `number ÷ 255.0`), but the spec doesn't currently include that as a field that's available in the Mustache template context.

After making this change, I was able to [generate and publish a full set of Xcode color templates](https://github.com/kreeger/base16-xcode) (and I love them!). [This is my Mustache template](https://github.com/kreeger/base16-xcode/blob/66e87c3363acab1034aff027a3c159fa48709b57/templates/default.mustache) for the Xcode color template, and [this is a resulting file](https://github.com/kreeger/base16-xcode/blob/66e87c3363acab1034aff027a3c159fa48709b57/Themes/base16-tomorrow-night.xccolortheme).

I'm willing to submit pull requests where necessary — let me know if you'd like this as an addition to the spec and I can get started, and I'll also open up a PR to get my Xcode template added to the list.

**Comment by belak** [comment]
This seems useful. I've added it to the [base16-builder-go](https://github.com/belak/base16-builder-go) for now until something can be agreed upon here.

**Comment by chriskempson** [comment]
It is useful 😄 Added to the builder guidelines: https://github.com/chriskempson/base16/blob/master/builder.md

**Comment by kreeger** [comment]
Thank you, @chriskempson!

**Comment by chriskempson** [comment]
You're welcome. I'll get round to adding it to the PHP builder soon.
