### ISSUE TITLE
Color scheme licensing

### ISSUE THREAD

**Issue by belak** [chriskempson/base16#59]
The problem nobody wants to deal with...

Before this was an easier question because all the schemes and templates were in one repository. Everything was MIT and that was how it had to be... however, now that there are multiple scheme repos, they could (potentially) have other licenses.

As I see it, there are a few possible options:
- Add a `license` field to each color scheme, possibly erroring on a missing license (or defaulting to MIT for at least all the schemes in the original builder, as that was the license of the base16-builder)
- Require all schemes to be licensed under the same license (either a specific license, or public domain)
- Move all scheme files back to one repo (a variation on "require the same license")

**Comment by chriskempson** [comment]
I'm in favour of letting people have the freedom to release their builders, schemes and templates under whatever licence they prefer. Trying to think if there are any negative sides to this?

It should perhaps be included in the spec that all builders, schemes and templates are released under a licence.

**Comment by belak** [comment]
In general, I think that's fine. The problem I ran into when I was working on the emacs templates was that emacs packages are traditionally released under the GPL. I wanted to pull in code that was GPL, but because the templates themselves were MIT, that isn't allowed.

Having no license on the schemes further complicates this, because if one user releases their scheme under (as an example) the GPL, it would not be valid to include this in any templates which are released as MIT because the MIT license is less restrictive than the GPL.

I'm no lawyer, so I don't know what the "correct" solution to this is, but I wanted to at least bring it up.

**Comment by chriskempson** [comment]
Perhaps a restriction should be that all schemes added to the schemes repo and all templates added to the templates repo should be under a particular licence? Without this anyone wishing to make use of a builder or the output of a builder in one of their projects would have to check each and every scheme and template for licencing issues. 

If people wish to release scheme or templates that are released under restrictive licences there could be another set of source repositories for these. Similar to how Linux distros manage their sources.

**Comment by belak** [comment]
That would solve this. Thanks for being willing to discuss it. :)

**Comment by chriskempson** [comment]
No problem. Thanks for raising this issue 😄

**Comment by belak** [comment]
Also, as clarification, perhaps it could be something along the lines of "MIT or more permissive", though I'm not sure if there's a standard "legal" way of saying that.
