### ISSUE TITLE
Clarify output filename

### ISSUE THREAD

**Issue by belak** [chriskempson/base16#60]
Right now the file name comes from taking `base16-`, calling `slugify` on the scheme name, and appending the extension.

It might be good to define the output filename because slugify isn't an "official" spec. :/

**Comment by chriskempson** [comment]
Agreed. I guess there are two solutions to this, defining the slug in the scheme files or making the slugging part of the spec. I'm leaning towards the former as it simplifies builders further.

**Comment by chriskempson** [comment]
Ended up going for the latter as I decided that scheme designs wouldn't necessarily know the correct format for the slug to be in.
