### ISSUE TITLE
Italics and bold

### ISSUE THREAD

**Issue by rafaeln** [chriskempson/base16#76]
Colorschemes like [seoul256](https://github.com/junegunn/seoul256.vim) give `htmlItalic` and `htmlBold` the attributes italic and bold, respectively. Base16 colorschemes don't. Maybe there's a design reason for that, but if other users like me prefer to see italic and bold instead of meaningless colors whenever they're editing markdown text, they can change the colorschemes manually thus:

```bash
cd base16-vim/colors
sed -ri '/Italic/ s/^([^,]*,){5} "(none)?/\1 "italic/' *vim
sed -ri '/Bold/ s/^([^,]*,){5} "(none)?/\1 "bold/' *vim
```

This issue was originally posted at chriskempson/base16-vim#128

**Comment by chriskempson** [comment]
Thanks for reposting this here. It was a while ago I made this design choice but I believe I originally wanted to avoid bold and italic as for syntax highlighting cues as I believed that colours were more easily identifiable. That and I think not all terminals have bold text enabled or perhaps not all fonts have a bold or italic variant and I wanted to try and ensure this looked the same for as many people as possible.

The colours you mention aren't actually meaningless, as you can see here: http://chriskempson.com/projects/base16 their uses are explained. Couple this up with the visual notations that markdown has e.g. **emphasis** and I think it is quite easy to see what is going on.

**Comment by rafaeln** [comment]
I see your point. Indeed, base16 seems tailored for people who don't have fancy terminals. Fancy terminals already support true color! There are, however, popular terminals that don't support true color but already support italics and bold, such as urxvt. I wonder if there is a way to check and only enable bold and italic in terminals that support them.

**Comment by belak** [comment]
So, for terminals, as far I know, colors 9-16 are actually "bold colors". Many terminals don't support bold separate from this... and I explicitly turn it off because most color schemes just define additional colors in place of making the text bold.
