### ISSUE TITLE
"bash: [: too many arguments" error when colourscheme applied to gnome-terminal

### ISSUE THREAD

**Issue by subhammridha** [chriskempson/base16#77]
After the recent update to your base16-shell package, my terminal throws the following error whenever it is opened:
`bash: [: too many arguments`
Earlier, this error wasn't being shown. I don't quite understand where the error is occurring. Could you please check and help me fix this.
I am using CentOS 7.3.

**Comment by chriskempson** [comment]
Please see: https://github.com/chriskempson/base16-shell/issues/91

**Comment by subhammridha** [comment]
Thanks for the timely update. Thanks a lot by the way.
