### ISSUE TITLE
Builder spec ambiguity: how to obtain scheme slug

### ISSUE THREAD

**Issue by iamthad** [chriskempson/base16#78]
The builder spec just says the slug is obtained from the scheme file, and doesn't specify how.

[The reference implementation](https://github.com/chriskempson/base16-builder-php) uses the PHP [slugify](https://github.com/cocur/slugify) package.

[My Python builder](https://github.com/iamthad/python_base16_builder) simply uses the name of the scheme file minus the extension. This produces identical results in most, but not all, cases.

It seems to me undesirable to link the spec to a specific PHP package. I'd propose using the scheme filename without extension as the scheme slug.

**Comment by belak** [comment]
I believe this was the intent. I recently updated the Go builder to do this because it was causing conflicting/missing themes.

**Comment by belak** [comment]
https://github.com/chriskempson/base16/issues/60

https://github.com/chriskempson/base16/blob/master/builder.md#workflow

    The theme filename should look like base16-[slug][extension]. Where the slug is taken from the scheme file name made lowercase with spaces replaced with dashes and extension is taken from /template/config.yaml.

**Comment by belak** [comment]
I think this should be closed because it looks like the spec is not ambiguous any more. Though, perhaps the reference builder isn't up to date?

**Comment by iamthad** [comment]
Indeed, the spec has been changed. And [your issue](https://github.com/chriskempson/base16-builder-php/issues/11) on the reference builder remains open. So I'll close this.
