### ISSUE TITLE
Override color_cursor for all base16 scripts.

### ISSUE THREAD

**Issue by Traap** [chriskempson/base16#81]
I am a Tmux / Vim / iTerm user.   I would like the ability to use the same color_cursor for all base16 scripts.  As an example, I like to use 00FFFF as my cursor color so that I can easily relocate it visually.

I use multiple monitors running Tmux with multiple pains and vim with multiple splits.    I find myself typing jkjkjkjkjkjkjkjk to locate the cursor as I switch between iTerm instances, Tmux pain, and Vim splits. 

Any guidance is appreciated.

**Comment by belak** [comment]
This seems a bit specific to be supported by the spec

**Comment by chriskempson** [comment]
Agreed, this wouldn't be added to the spec but I get the impression that @Traap is asking how you'd achieve this. I believe you'd have to edit the template files in base16-vim and base16-iterm2 and change both cursor colour definitions (https://github.com/chriskempson/base16-vim/blob/master/templates/default.mustache#L142) and (https://github.com/chriskempson/base16-builder/blob/master/templates/iterm2/dark.itermcolors.erb#L207). 

Unfortunately the iTerm2 theme hasn't be converted to the new builder system yet so you'd need to use the old builder (https://github.com/chriskempson/base16-builder) to build your changes.

**Comment by Traap** [comment]
@chriskempson Thank you for the guidance.  @belak You are correct.  It is specific.  Guidance was all I needed.  Thank you both.
