### ISSUE TITLE
Hover to preview

### ISSUE THREAD

**Issue by CallumHoward** [chriskempson/base16#83]
Sorry if this is common knowledge, but what happened to the nice hover to preview feature on http://chriskempson.github.io/base16/ ?

It used to be like this:
<img width="687" alt="screen shot 2017-03-10 at 10 32 25 am" src="https://cloud.githubusercontent.com/assets/7144420/23775466/e7c0606e-057c-11e7-8dc5-119ac44e509f.png">

Now it appears like this:
<img width="842" alt="screen shot 2017-03-10 at 10 33 18 am" src="https://cloud.githubusercontent.com/assets/7144420/23775487/04e99854-057d-11e7-9614-a453fa116561.png">

Tested on Safari and Chrome on MacOS

**Comment by chriskempson** [comment]
Not sure sorry but that website is deprecated. I'd like a website that can be built automatically and regenerated each time a new scheme file is added but haven't given to much thought as to the best way of doing this yet.
