### ISSUE TITLE
base16-builder-perl

### ISSUE THREAD

**Issue by loomer** [chriskempson/base16#85]
A Perl implementation of a base16 builder.
https://github.com/loomer/base16-builder-perl
Checked the output against the the output of the ruby version. Let me know if there is something that needs fixing.

**Comment by chriskempson** [comment]
Looks good. Fancy adding it to the list of builder repositories? https://github.com/chriskempson/base16/blob/master/README.md#builder-repositories

**Comment by loomer** [comment]
Sure thing
#86
