### ISSUE TITLE
Proposal to simplify list repos

### ISSUE THREAD

**Issue by belak** [chriskempson/base16#95]
Right now, there are 2 repos which need to be fetched to even look up which schemes and templates need to be fetched. I would propose merging these into one repo with multiple files.

Right now the layout is like this:

```
base16-schemes-source/list.yaml
base16-templates-source/list.yaml
```

But we could move to something like this:

```
base16-sources/schemes.yaml
base16-sources/templates.yaml
```

If you feel strongly about this I can drop this.

**Comment by chriskempson** [comment]
What would be the benefit of merging these?

**Comment by belak** [comment]
One less repo to keep track of for me... plus one less repo for builders to clone. Not a huge difference, just a small convenience.

**Comment by chriskempson** [comment]
What if someone wants to use their own scheme repo but build all templates and vice versa? The small convenience seems like it imposes restrictions too.

**Comment by belak** [comment]
Makes sense. I don't think this is worth it then.
