### ISSUE TITLE
Support for termguicolors

### ISSUE THREAD

**Issue by chrisbra** [chriskempson/base16#98]
Hi,
I am just wondering, does this colorscheme support truecolor mode in the terminal (:set termguicolors in Vim)?

Thanks.

**Comment by chriskempson** [comment]
As far as I can see `termguicolors` will make use of the GUI colours specified in base16 so I'd imagine so.

**Comment by chrisbra** [comment]
Does it use any of `has("gui")` conditions? those would have to be removed to properly support it.

**Comment by chriskempson** [comment]
I guess this issue should really be in the vim repo. You can see the code over there too: https://github.com/chriskempson/base16-vim/blob/master/templates/default.mustache

There is one `has('gui_running')` condition as you can see but I don't think it will affect truecolour support.

**Comment by chrisbra** [comment]
Ah sorry, for selecting the wrong repository. Yes thanks looks good. (You might want to mention, that it supports truecolor in the terminal as well as 256 colors in the vim-repo.) Thanks!
